//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoEncuentro.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PUNTO_ENCUENTRO_Entidades : DbContext
    {
        public PUNTO_ENCUENTRO_Entidades()
            : base("name=PUNTO_ENCUENTRO_Entidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_AsistenciaEvento> t_AsistenciaEvento { get; set; }
        public virtual DbSet<t_EstadoCivil> t_EstadoCivil { get; set; }
        public virtual DbSet<t_Evento> t_Evento { get; set; }
        public virtual DbSet<t_TipoSexo> t_TipoSexo { get; set; }
        public virtual DbSet<t_TipoUsuario> t_TipoUsuario { get; set; }
        public virtual DbSet<t_UsuarioLogin> t_UsuarioLogin { get; set; }
        public virtual DbSet<t_Usuarios> t_Usuarios { get; set; }
    }
}
