//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoEncuentro.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Usuarios()
        {
            this.t_AsistenciaEvento = new HashSet<t_AsistenciaEvento>();
            this.t_AsistenciaEvento1 = new HashSet<t_AsistenciaEvento>();
            this.t_UsuarioLogin = new HashSet<t_UsuarioLogin>();
        }
    
        public int numIdUsuario { get; set; }
        public string tipoIdNumUsuario { get; set; }
        public string primerNombre { get; set; }
        public string segundoNombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public Nullable<int> tipoUsuario { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string Celular { get; set; }
        public string NumeroFijo { get; set; }
        public string CorreoElectronico { get; set; }
        public string Ocupacion { get; set; }
        public Nullable<int> Sexo { get; set; }
        public Nullable<int> EstadoCivil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_AsistenciaEvento> t_AsistenciaEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_AsistenciaEvento> t_AsistenciaEvento1 { get; set; }
        public virtual t_EstadoCivil t_EstadoCivil { get; set; }
        public virtual t_TipoSexo t_TipoSexo { get; set; }
        public virtual t_TipoUsuario t_TipoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_UsuarioLogin> t_UsuarioLogin { get; set; }
    }
}
